version: '3'
 
services:

  db1:  
    image: mysql:8
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: demo1 
      MYSQL_DATABASE: demo1
      MYSQL_USER: demo1
      MYSQL_PASSWORD: demo1
    ports:
      - "6034:3306"
    volumes:
      - dbdata1:/var/lib/mysql

  db2:
    image: mysql:8
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: demo2
      MYSQL_DATABASE: demo2
      MYSQL_USER: demo2
      MYSQL_PASSWORD: demo2
    ports:
      - "6035:3306"
    volumes:
      - dbdata2:/var/lib/mysql

  db3:
    image: mysql:8
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: demo3
      MYSQL_DATABASE: demo3
      MYSQL_USER: demo3
      MYSQL_PASSWORD: demo3
    ports:
      - "6036:3306"
    volumes:
      - dbdata3:/var/lib/mysql

  db4:
    image: mysql:8
    container_name: db4
    environment:
      MYSQL_ROOT_PASSWORD: demo4
      MYSQL_DATABASE: demo4
      MYSQL_USER: demo4
      MYSQL_PASSWORD: demo4
    ports:
      - "6037:3306"
    volumes:
      - dbdata4:/var/lib/mysql

  db5:
    image: mysql:8
    container_name: db5
    environment:
      MYSQL_ROOT_PASSWORD: demo5
      MYSQL_DATABASE: demo5
      MYSQL_USER: demo5
      MYSQL_PASSWORD: demo5
    ports:
      - "6038:3306"
    volumes:
      - dbdata5:/var/lib/mysql

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on: 
     - phpmyadmin
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/etc:/etc/nginx/
    restart: always
    


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db1
      - db2
      - db3
      - db4
      - db5
    environment:
      PMA_HOSTS: db1, db2, db3, db4, db5
      PMA_PORTS: 3306, 3306, 3306, 3306, 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - db1
      - db2
      - db3
      - db4
      - db5
    ports:
      - 8080:80
volumes:
  dbdata1:
  dbdata2:
  dbdata3:
  dbdata4:
  dbdata5: